### ISSUE TITLE
POLG hg38 coordinates

### ISSUE THREAD

**Issue by bw2** [Clinical-Genomics/stranger#41]
I think the POLG hg38 coordinates might be wrong here:

https://github.com/moonso/stranger/blob/master/stranger/resources/variant_catalog_grch38.json#L1220-L1221

In my own records the CTG repeat is @ chr15:89333590-89333628

**Comment by dnil** [comment]
Indeed, those looked conspicuously similar to hg19 coordinates! Thank you kindly!

**Comment by dnil** [comment]
Oki, think I got it now: someone showed it to me like two units, so I guess I'm keeping it like that for now. But your CTG should be identical to the POLG_II in the Stranger definition file, and for sure it was one base off for each!
