### ISSUE TITLE
Variant catalog and DAB1 

### ISSUE THREAD

**Issue by A97paupic** [Clinical-Genomics/stranger#42]
Hi,
in the latest version of the variant catalog there are three different variantIds for DAB1; DAB1_ATTTT1, DAB1_ATTTC and DAB1_ATTTT2. DAB1_ATTTC is the clinically significant one but this is not recognised by scout as the status field is left blank. For other variants with more than one variantId there seems to be the rule to give the clinically significant variant the same name as given for the LocusId. For instance, ATXN7 has two variantId; ATXN7 and ATXN7_GCC. When uploaded to scout they all seem to get a status annotation for the most significant variant in multiple variantId loci. 

It might be a reason for the naming of DAB1 variantIds in the catalog but if not, it's probably an honest mistake?

Kind Regards,
Paul

**Comment by dnil** [comment]
No, that seems just like a mistake - possibly a little bit of a legacy thing as well, but with the way we use it currently, it should certainly be DAB1 only for the ATTTC insertion. Good call! On our end, it would still be displayed in Scout given appropriate filters, but not annotated as nicely as intended.
