### ISSUE TITLE
Release 0.8.1 missing?

### ISSUE THREAD

**Issue by Stikus** [Clinical-Genomics/stranger#44]
Hello.
I see some commits mentioning version 0.8.1 are pushed 11 days ago, but no new release was published here: https://github.com/Clinical-Genomics/stranger/releases

Is release missing or still not completed yet?

**Comment by Stikus** [comment]
@dnil Hello, any news about release?

**Comment by dnil** [comment]
Thanks for the poke: I have to do something about my alerts.. Version looks bumped, so Im guessing the release was simply not wrapped up. Just a moment..

**Comment by dnil** [comment]
Ok, done. Cheers folks!
