### ISSUE TITLE
Add novel repeat expansions 

### ISSUE THREAD

**Issue by bopohdr** [Clinical-Genomics/stranger#47]
Hi ! 

Could you, please, add recently described repeat expansion disorders:
1) SCA4 https://pubmed.ncbi.nlm.nih.gov/38035881/
2) SCA27B https://pubmed.ncbi.nlm.nih.gov/37165652/
Both of them appear to be quite common.

**Comment by dnil** [comment]
Hi!

Firstly, the locus definitions supplied with the Stranger software are intended as a demo, not a definitive set.

If you are curious about what we use in clinical production, have a look over at https://github.com/Clinical-Genomics/reference-files/tree/master/rare-disease/disease_loci/ExpansionHunter-v5.0.0. Both SCA4 and SCA27B are in there, though the latter is bound to be a bit shaky on short read sequencing, with not uncommon large intermediate alleles. 

That said, the demo could certainly do with an update; good idea!

Out of what probably is a narrow minded perspective, I still prefer https://www.medrxiv.org/content/10.1101/2023.10.03.23296230v1 to be the primary reference for SCA4/*ZFHX3*; it was out a month before the other paper was submitted, but unfortunately they missed referencing it. Its not important - but I hope the chronology will be cleared up once ours is done on peer-review, if ever.. 😸 

Anyway, cool that you are using Stranger! Would you care to share your experiences a bit?

**Comment by bopohdr** [comment]
thanks ! 
We actually got validated expansionhunter+STRanger+REViewer pipeline for the majority of exonic STRs and got them through external SCA QA (even though they did not like that we use exomes) and now use in diagnostics from exomes! Thanks for developing and maintaining!

**Comment by dnil** [comment]
Super! Interesting, and with like an unmodified capture kit, not with extra probes catering to the expansions? Cool, though I would also really recommend genomes - or LRS, though I guess that may not be for large scale diagnostics in the very near term. 😊

**Comment by bopohdr** [comment]
yes, regular Twist capture. We do see only exonic (some near exonic as well(, but this is already more types than we can get with PCR.
LRS is of course the promising next step, but not sure whether tools like expansionhunter are ready for those, as the STRs are still variable in reads...
