### ISSUE TITLE
Annotate multi-sample VCF

### ISSUE THREAD

**Issue by fellen31** [Clinical-Genomics/stranger#73]
Would it be possible to annotate a multi-sample VCF? 

Or if not, give an error if a multi-sample VCF is supplied 🙂

**Comment by dnil** [comment]
I believe that is the intention, and is the standard operation procedure for ExHu. Is there an issue with multisample files in trgt mode? If you are not fixing it yourself anyway, please add an example line or path to input that is failing!

**Comment by fellen31** [comment]
Hm, maybe I have two separate issues/questions. 

1. Let's say I have a VCF with 2 samples, one with an expanded allele and one without. How would `STR_STATUS=...` then be decided for each sample since it's in the INFO tag only? 
2. Here's a [multisample.vcf.gz](https://github.com/user-attachments/files/16273754/multisample.vcf.gz) where stranger produces a non valid [multisample_stranger.vcf.gz](https://github.com/user-attachments/files/16273759/multisample_stranger.vcf.gz), guessing it's because of the normalisation.

```
stranger \
    --trgt \
    multisample.vcf.gz \
    --repeats-file variant_catalog_grch38.json | gzip --no-name > multisample_stranger.vcf.gz
```

**Comment by dnil** [comment]
Let’s see! 😊

For 1 we would just flag it according to the worst consequence for whichever individual. This is standard procedure for all INFO level annotation (though there are some exceptions like CSQ fields). Scout or other ds programs would have to deal with the genotypes, if they are even given with any clarity beyond the affected one. On the same row you would expect at most two alleles, typically the ref and the expanded.

For 2 I can’t help from vacation - will get back to it in a few weeks if you haven’t solved it already! 🏝️

**Comment by fellen31** [comment]
Alright, good to know that it's according to the worst consequence, I wasn't aware that's how it worked.

There's no rush!

**Comment by dnil** [comment]
Hi @fellen31! This one slipped - its dangerous to start to answer... 😁 Fixing now.
